testing_inspirational_quotes = False
model_name_authors = 'inspirational_quotes_authors'
model_name_quotes = 'inspirational_quotes_quotes'
dataset_file = "quotes_unmassaged.json"
generated_dataset_file_quotes = "quotes.txt"
generated_dataset_file_authors = "authorsUrban.txt"
current_path_dir = 'models/inspirational_quotes'
current_path = 'inspirational_quotes'
number_of_tweets_to_generate = 10000
number_of_authors_to_generate = 5000
number_of_quotes_to_generate = 5000
save_tweets_to_file = True
temperature = [0.2, 0.4, 0.6, 0.7, 0.8, 0.9, 1.0, 1.0]
